# Generated by Django 5.2.4 on 2025-10-04 12:14

import schedule.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', schedule.models.CustomUserManager()),
            ],
        ),
    ]
