# Generated by Django 5.2.4 on 2025-10-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_viewer_name_viewer_age_viewer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='avatar',
            field=models.ImageField(default='profile_images/standart_avatar.png', upload_to='profile_images/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='profile_images/standart_avatar.png', upload_to='profile_images/'),
        ),
    ]
