# Generated by Django 5.2.4 on 2025-10-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_viewer_avatar_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='online_available',
            field=models.BooleanField(default=False, help_text='Отметьте, если у фильма есть онлайн просмотр (видеофайл)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загрузите видео для онлайн-просмотра (mp4/ogg/webm).', null=True, upload_to='movie_videos/'),
        ),
    ]
