# Generated by Django 5.2.4 on 2025-10-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_movie_online_available_movie_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='online_available',
        ),
        migrations.AddField(
            model_name='movie',
            name='has_online_viewing',
            field=models.BooleanField(default=False, verbose_name='Есть онлайн просмотр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.genre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='movie_videos/', verbose_name='Видео для онлайн просмотра'),
        ),
    ]
