# Generated by Django 5.2.4 on 2025-10-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='avatar',
            field=models.ImageField(default='profile_images/standart_avatar.png', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
