# Generated by Django 5.2.4 on 2025-10-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_viewer_is_online_alter_viewer_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.AddField(
            model_name='movie',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='has_trailer',
            field=models.BooleanField(default=False, verbose_name='Есть трейлер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_file',
            field=models.FileField(blank=True, null=True, upload_to='movie_trailers/', verbose_name='Файл трейлера'),
        ),
    ]
