# Generated by Django 5.2.4 on 2025-10-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_remove_movie_description_movie_full_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', '🎬 В планах'), ('watching', '👀 Смотрю'), ('completed', '✅ Просмотрено'), ('favorite', '❤️ Любимое'), ('dropped', '💤 Брошено'), ('rewatch', '🔁 Пересмотреть')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='schedule.movie')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='schedule.viewer')),
            ],
            options={
                'unique_together': {('viewer', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='schedule.movie')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='schedule.viewer')),
            ],
            options={
                'unique_together': {('viewer', 'movie')},
            },
        ),
    ]
