# Generated by Django 5.2.4 on 2025-10-18 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_bookmark_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='status',
            field=models.CharField(choices=[('nothing', '-----'), ('planned', '🎬 В планах'), ('watching', '👀 Смотрю'), ('completed', '✅ Просмотрено'), ('favorite', '❤️ Любимое'), ('dropped', '💤 Брошено'), ('rewatch', '🔁 Пересмотреть')], max_length=20),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Запрошено'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_from', to='schedule.viewer')),
                ('to_viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_to', to='schedule.viewer')),
            ],
            options={
                'unique_together': {('from_viewer', 'to_viewer')},
            },
        ),
    ]
