# Generated by Django 5.2.4 on 2025-10-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_message_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.viewer')),
            ],
            options={
                'unique_together': {('row', 'column')},
            },
        ),
    ]
