# Generated by Django 5.2.4 on 2025-10-21 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_globalchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalchatmessage',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalchatmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_messages', to='schedule.viewer'),
        ),
        migrations.AlterField(
            model_name='globalchatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_messages', to='schedule.viewer'),
        ),
    ]
