# Generated by Django 5.2.4 on 2025-10-24 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_globalchatmessage_is_private_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.FloatField(default=0.0)),
                ('watched_trailer', models.BooleanField(default=False)),
                ('watched_movie', models.BooleanField(default=False)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='schedule.movie')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='schedule.viewer')),
            ],
            options={
                'unique_together': {('viewer', 'movie')},
            },
        ),
    ]
