# Generated by Django 5.2.4 on 2025-10-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_promocode_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, verbose_name='Макс. использований'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Уже использовано'),
        ),
    ]
