# Generated by Django 5.2.4 on 2025-10-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_promocode_max_uses_promocode_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=6, verbose_name='Ціна квитка'),
        ),
    ]
