# Generated by Django 5.2.4 on 2025-11-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_session_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='status',
            field=models.CharField(choices=[('nothing', '-----'), ('planned', '🎬 У планах'), ('watching', '👀 Дивлюся'), ('completed', '✅ Переглянуто'), ('favorite', '❤️ Улюблене'), ('dropped', '💤 Кинуто'), ('rewatch', '🔁 Переглянути ще раз')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловічий'), ('female', 'Жіночий')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Запрошено'), ('accepted', 'Прийнято'), ('rejected', 'Відхилено')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Повний опис'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='schedule.genre', verbose_name='Жанри'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='has_online_viewing',
            field=models.BooleanField(default=False, verbose_name='Є онлайн перегляд'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='has_trailer',
            field=models.BooleanField(default=False, verbose_name='Є трейлер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='movie_videos/', verbose_name='Відео для онлайн перегляду'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, verbose_name='Макс. використань'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Вже використано'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Поповнення'), ('spend', 'Списання'), ('promo', 'Промокод')], max_length=10),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловічий'), ('female', 'Жіночий')], max_length=10, null=True),
        ),
    ]
