# Generated by Django 5.2.4 on 2025-11-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_alter_bookmark_status_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='initial_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Базова середня оцінка'),
        ),
    ]
