# Generated by Django 5.2.4 on 2025-11-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_movie_initial_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='initial_rating',
        ),
    ]
