# Generated by Django 5.2.4 on 2025-11-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_onlinesession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineSession',
        ),
    ]
