# Generated by Django 5.2.4 on 2025-11-18 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_delete_onlinesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveWatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_session', to='schedule.movie')),
            ],
        ),
    ]
